# Generated by Django 4.2.6 on 2024-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='chat_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='messages',
            field=models.JSONField(default=dict),
        ),
    ]
