# Generated by Django 5.0.3 on 2024-03-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='chat_list',
            field=models.JSONField(default=list),
        ),
    ]
