# Generated by Django 5.0.3 on 2024-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users_last_online_alter_users_chat_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=150), max_length=150),
        ),
    ]
