# Generated by Django 5.0.3 on 2024-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_users_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='new_avatar',
            field=models.ImageField(default='//', upload_to='avatars_users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='display_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
